# Generated by Django 4.1.6 on 2023-03-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MYSITEBASE2',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='LocationName',
            new_name='locationName',
        ),
        migrations.AddField(
            model_name='item',
            name='itemLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.location'),
        ),
    ]
